spring:
  datasource:
    url: jdbc:h2:mem:f1simple;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

openf1:
  base-url: https://api.openf1.org/v1

springdoc:
  swagger-ui:
    path: /swagger
